### ISSUE TITLE
Should the code for the full file should be shown inline or just the link should be in the beginning

### ISSUE THREAD

**Issue by joelostblom** [open-resources/dash_curriculum#27]
Currently different chapters do different things

**Comment by Coding-with-Adam** [comment]
I'm not sure what you mean here Joel. Can you please clarify with an example.

**Comment by joelostblom** [comment]
Code + file download:
![image](https://user-images.githubusercontent.com/4560057/163817753-c4744deb-9e77-4c13-8a15-a54ea0da922d.png)

Just file download:
![image](https://user-images.githubusercontent.com/4560057/163817812-f8016ac2-d4c8-4e70-baf8-1b16827a7477.png)

**Comment by Coding-with-Adam** [comment]
Oh, I see. I think we could do both in case people want to just copy the code and paste into their IDE instead of downloading it. 

But, since initial downloadable code might be very long eventually, I think we can put the code inside an accordion so people can open it up only if they want to copy it and close it thereafter. 

What do you two think?

**Comment by joelostblom** [comment]
>But, since initial downloadable code might be very long eventually, I think we can put the code inside an accordion so people can open it up only if they want to copy it and close it thereafter.

Great idea! For me this would be enough, not sure if there is any advantage to letting them also download the file, but I am also not really against it :shrug:

**Comment by Coding-with-Adam** [comment]
This will now be implemented for all chapters. I did this for Chapter 2. And group will be informed about his on Friday April 22.
